project:
  type: book
  output-dir: E:/CASA0023diary
book:
  title: "CASA 0023 Learning Diary"
  author: "Yihan Liu"
  date: "2024/2/22"
  chapters:
    - index.qmd
    - week1.qmd
    - week2.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

