# Week 1

## Summary

## Applications

Remote sensing, which collects information about the Earth's surface by assessing reflected and radiated energy over long distances, is now widely used in fields such as agriculture, forestry, climate detection, water resource management, and urban planning.

A specific example of the application of remote sensing data preprocessing, spectral feature comparison methods learnt in the classroom is the application of remote sensing for surface temperature analysis of land cover change in the Greater Cairo region of Egypt (Aboelnour, M., & Engel, B. A. 2018). The study used Landsat datasets with different temporal dimensions to analyse land cover change through classification and post-classification change detection techniques using remote sensing image preprocessing, image classification, and other methods, in order to help policy makers to predict and plan for the future development of the Greater Cairo region in Egypt, to achieve long term sustainability of soil and water resources, and to cope with the impacts of climate change.

## Reflection

What impressed me most about this week's course was the powerful ability that remote sensing technology gives us to observe and understand information about features on the Earth's surface. For example, the spectral features I extracted from the Sentinel and Landsat datasets in the hands-on class can be used to classify and compare different types of features, and identify the characteristics and distribution of various features on the Earth. In my undergraduate stage, I had studied the course of land management, at that time, the teacher mentioned that remote sensing can be used in land use and cover change detection and other aspects to provide basic information for land planning and management, and this class gave me the opportunity to process remote sensing data and analyse the land cover type of hands-on practice, which gave me a deeper understanding of what I had learnt before, and at the same time, it also made me look forward to the content of the next study, which will bring me more The class has given me a deeper understanding of what I have learnt, and also made me look forward to what I will learn next, which will bring me more inspiration.

This is a book created from markdown and executable code.

See @knuth84 for additional discussion of literate programming.

```{r}
1 + 1
```
